In [172]:
import pandas as pd 

raw_data = pd.read_csv(r'C:\Users\sandi\Documents\Study\project\World Demographic Index\Data\WPP2024_GEN_F01_DEMOGRAPHIC_INDICATORS_1950-2023.csv')
data = raw_data.copy()
data.head()

C:\Users\sandi\AppData\Local\Temp\ipykernel_12940\24974247.py:3: DtypeWarning: Columns (0: Unnamed: 0, 1: Unnamed: 3, 2: Unnamed: 4, 3: Unnamed: 7, 4: Unnamed: 9, 5: Unnamed: 10, 6: Unnamed: 15, 7: Unnamed: 16, 8: Unnamed: 17, 9: Unnamed: 19, 10: Unnamed: 21, 11: Unnamed: 25, 12: Unnamed: 26, 13: Unnamed: 27, 14: Unnamed: 28, 15: Unnamed: 29, 16: Unnamed: 33, 17: Unnamed: 34, 18: Unnamed: 35, 19: Unnamed: 36, 20: Unnamed: 37, 21: Unnamed: 38, 22: Unnamed: 39, 23: Unnamed: 40, 24: Unnamed: 41, 25: Unnamed: 42, 26: Unnamed: 43, 27: Unnamed: 44, 28: Unnamed: 45, 29: Unnamed: 46, 30: Unnamed: 47, 31: Unnamed: 49, 32: Unnamed: 50, 33: Unnamed: 51, 34: Unnamed: 52, 35: Unnamed: 53, 36: Unnamed: 54, 37: Unnamed: 55, 38: Unnamed: 56, 39: Unnamed: 57, 40: Unnamed: 58, 41: Unnamed: 59, 42: Unnamed: 60, 43: Unnamed: 61, 44: Unnamed: 62, 45: Unnamed: 64) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data = pd.read_csv(r'C:\Users\sandi\Documents\Study\project\World Demographic Index\Data\WPP2024_GEN_F01_DEMOGRAPHIC_INDICATORS_1950-2023.csv')

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,United Nations,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,Population Division,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [173]:
data.columns = data.iloc[15]
data = data.iloc[16:].reset_index(drop=True)
data

15,Index,Variant,"Region, subregion, country or area *",Notes,Location code,ISO3 Alpha-code,ISO2 Alpha-code,SDMX code**,Type,Parent code,...,"Male Mortality before Age 60 (deaths under age 60 per 1,000 male live births)","Female Mortality before Age 60 (deaths under age 60 per 1,000 female live births)","Mortality between Age 15 and 50, both sexes (deaths under age 50 per 1,000 alive at age 15)","Male Mortality between Age 15 and 50 (deaths under age 50 per 1,000 males alive at age 15)","Female Mortality between Age 15 and 50 (deaths under age 50 per 1,000 females alive at age 15)","Mortality between Age 15 and 60, both sexes (deaths under age 60 per 1,000 alive at age 15)","Male Mortality between Age 15 and 60 (deaths under age 60 per 1,000 males alive at age 15)","Female Mortality between Age 15 and 60 (deaths under age 60 per 1,000 females alive at age 15)",Net Number of Migrants (thousands),"Net Migration Rate (per 1,000 population)"
0,1,Estimates,World,NaN,900,NaN,NaN,1,World,0,...,581,497,239,269,208,375,426,323,0,0
1,2,Estimates,World,NaN,900,NaN,NaN,1,World,0,...,567,488,230,256,203,365,413,316,0,0
2,3,Estimates,World,NaN,900,NaN,NaN,1,World,0,...,546,475,217,239,196,351,393,307,0,0
3,4,Estimates,World,NaN,900,NaN,NaN,1,World,0,...,536,467,211,231,191,343,384,301,0,0
4,5,Estimates,World,NaN,900,NaN,NaN,1,World,0,...,522,456,203,221,185,332,372,293,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21978,21979,Estimates,Wallis and Futuna Islands,2.0,876,WLF,WF,876,Country/Area,957,...,92,94,29,27,31,79,82,76,- 0,-14.3
21979,21980,Estimates,Wallis and Futuna Islands,2.0,876,WLF,WF,876,Country/Area,957,...,90,92,28,26,30,77,81,75,- 0,-6.1
21980,21981,Estimates,Wallis and Futuna Islands,2.0,876,WLF,WF,876,Country/Area,957,...,103,100,32,31,33,88,94,83,- 0,-6.1
21981,21982,Estimates,Wallis and Futuna Islands,2.0,876,WLF,WF,876,Country/Area,957,...,87,89,27,25,29,75,78,72,- 0,-11.0
21982,21983,Estimates,Wallis and Futuna Islands,2.0,876,WLF,WF,876,Country/Area,957,...,86,88,27,25,29,74,77,71,- 0,-9.4

I want to do analysis on India compare with World data.

In [13]:
data = data[data['Region, subregion, country or area *'].isin(['World', 'India', 'China'])].reset_index(drop=True)
data

15,Index,Variant,"Region, subregion, country or area *",Notes,Location code,ISO3 Alpha-code,ISO2 Alpha-code,SDMX code**,Type,Parent code,...,"Male Mortality before Age 60 (deaths under age 60 per 1,000 male live births)","Female Mortality before Age 60 (deaths under age 60 per 1,000 female live births)","Mortality between Age 15 and 50, both sexes (deaths under age 50 per 1,000 alive at age 15)","Male Mortality between Age 15 and 50 (deaths under age 50 per 1,000 males alive at age 15)","Female Mortality between Age 15 and 50 (deaths under age 50 per 1,000 females alive at age 15)","Mortality between Age 15 and 60, both sexes (deaths under age 60 per 1,000 alive at age 15)","Male Mortality between Age 15 and 60 (deaths under age 60 per 1,000 males alive at age 15)","Female Mortality between Age 15 and 60 (deaths under age 60 per 1,000 females alive at age 15)",Net Number of Migrants (thousands),"Net Migration Rate (per 1,000 population)"
0,1,Estimates,World,NaN,900,NaN,NaN,1,World,0,...,581,497,239,269,208,375,426,323,0,0
1,2,Estimates,World,NaN,900,NaN,NaN,1,World,0,...,567,488,230,256,203,365,413,316,0,0
2,3,Estimates,World,NaN,900,NaN,NaN,1,World,0,...,546,475,217,239,196,351,393,307,0,0
3,4,Estimates,World,NaN,900,NaN,NaN,1,World,0,...,536,467,211,231,191,343,384,301,0,0
4,5,Estimates,World,NaN,900,NaN,NaN,1,World,0,...,522,456,203,221,185,332,372,293,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,8732,Estimates,India,NaN,356,IND,IN,356.0,Country/Area,5501,...,223,170,73,89,56,164,191,135,- 979,-0.7
218,8733,Estimates,India,NaN,356,IND,IN,356.0,Country/Area,5501,...,229,172,71,87,55,171,200,139,- 74,-0.1
219,8734,Estimates,India,NaN,356,IND,IN,356.0,Country/Area,5501,...,278,213,92,111,72,220,252,184,- 349,-0.2
220,8735,Estimates,India,NaN,356,IND,IN,356.0,Country/Area,5501,...,208,155,67,82,50,154,181,126,- 1 353,-1.0
221,8736,Estimates,India,NaN,356,IND,IN,356.0,Country/Area,5501,...,204,150,65,80,49,151,178,122,- 979,-0.7

I remove this column "'Index','Notes','ISO2 Alpha-code','SDMX code**', 'Parent code'" because it has no use for my analysis. only keep ISO3 Alpha-code: International standard country code (letter 3) because if i want to combine my UN data with world bank dataset. this country_code would become useful.

In [14]:
data.drop(columns=['Index','Notes','ISO2 Alpha-code','SDMX code**', 'Parent code'], inplace=True)
data

15,Variant,"Region, subregion, country or area *",Location code,ISO3 Alpha-code,Type,Year,"Total Population, as of 1 January (thousands)","Total Population, as of 1 July (thousands)","Male Population, as of 1 July (thousands)","Female Population, as of 1 July (thousands)",...,"Male Mortality before Age 60 (deaths under age 60 per 1,000 male live births)","Female Mortality before Age 60 (deaths under age 60 per 1,000 female live births)","Mortality between Age 15 and 50, both sexes (deaths under age 50 per 1,000 alive at age 15)","Male Mortality between Age 15 and 50 (deaths under age 50 per 1,000 males alive at age 15)","Female Mortality between Age 15 and 50 (deaths under age 50 per 1,000 females alive at age 15)","Mortality between Age 15 and 60, both sexes (deaths under age 60 per 1,000 alive at age 15)","Male Mortality between Age 15 and 60 (deaths under age 60 per 1,000 males alive at age 15)","Female Mortality between Age 15 and 60 (deaths under age 60 per 1,000 females alive at age 15)",Net Number of Migrants (thousands),"Net Migration Rate (per 1,000 population)"
0,Estimates,World,900,NaN,World,1950,2 471 424,2 493 093,1 241 432,1 251 661,...,581,497,239,269,208,375,426,323,0,0
1,Estimates,World,900,NaN,World,1951,2 514 762,2 536 927,1 263 362,1 273 565,...,567,488,230,256,203,365,413,316,0,0
2,Estimates,World,900,NaN,World,1952,2 559 092,2 584 086,1 287 093,1 296 993,...,546,475,217,239,196,351,393,307,0,0
3,Estimates,World,900,NaN,World,1953,2 609 080,2 634 106,1 312 355,1 321 751,...,536,467,211,231,191,343,384,301,0,0
4,Estimates,World,900,NaN,World,1954,2 659 132,2 685 895,1 338 531,1 347 364,...,522,456,203,221,185,332,372,293,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,Estimates,India,356,IND,Country/Area,2019.0,1 382 090,1 389 030,717 351,671 679,...,223,170,73,89,56,164,191,135,- 979,-0.7
218,Estimates,India,356,IND,Country/Area,2020.0,1 395 971,1 402 618,724 175,678 442,...,229,172,71,87,55,171,200,139,- 74,-0.1
219,Estimates,India,356,IND,Country/Area,2021.0,1 409 264,1 414 204,729 924,684 280,...,278,213,92,111,72,220,252,184,- 349,-0.2
220,Estimates,India,356,IND,Country/Area,2022.0,1 419 143,1 425 423,735 531,689 892,...,208,155,67,82,50,154,181,126,- 1 353,-1.0
221,Estimates,India,356,IND,Country/Area,2023.0,1 431 703,1 438 070,741 883,696 186,...,204,150,65,80,49,151,178,122,- 979,-0.7

Checking the datatype and convert them

In [15]:
# check what types of space included into data
print(repr(data['Total Population, as of 1 January (thousands)'].iloc[0] ))
# we can see the data contain space. we should remove this
print(repr(data['Population Sex Ratio, as of 1 July (males per 100 females)'].iloc[0])) # ok 
print(repr(data['Female Mortality before Age 40 (deaths under age 40 per 1,000 female live births)'].iloc[0]))
# integer data contain space. remove this.

' 2 471 424'
'99.2'
'   356'

In [16]:
# check which column data contained space. 
column_contained_space = [col for col in data.columns if data[col].astype(str).str.contains(r"\s+").any()] # any() function check whole column if any one value is true it flagged that column as true otherwise false
column_contained_space

['Total Population, as of 1 January (thousands)',
 'Total Population, as of 1 July (thousands)',
 'Male Population, as of 1 July (thousands)',
 'Female Population, as of 1 July (thousands)',
 'Natural Change, Births minus Deaths (thousands)',
 'Population Change (thousands)',
 'Births (thousands)',
 'Births by women aged 15 to 19 (thousands)',
 'Sex Ratio at Birth (males per 100 female births)',
 'Total Deaths (thousands)',
 'Male Deaths (thousands)',
 'Female Deaths (thousands)',
 'Infant Deaths, under age 1 (thousands)',
 'Under-Five Deaths, under age 5 (thousands)',
 'Under-Five Mortality (deaths under age 5 per 1,000 live births)',
 'Mortality before Age 40, both sexes (deaths under age 40 per 1,000 live births)',
 'Male Mortality before Age 40 (deaths under age 40 per 1,000 male live births)',
 'Female Mortality before Age 40 (deaths under age 40 per 1,000 female live births)',
 'Mortality before Age 60, both sexes (deaths under age 60 per 1,000 live births)',
 'Male Mortality before Age 60 (deaths under age 60 per 1,000 male live births)',
 'Female Mortality before Age 60 (deaths under age 60 per 1,000 female live births)',
 'Mortality between Age 15 and 50, both sexes (deaths under age 50 per 1,000 alive at age 15)',
 'Male Mortality between Age 15 and 50 (deaths under age 50 per 1,000 males alive at age 15)',
 'Female Mortality between Age 15 and 50 (deaths under age 50 per 1,000 females alive at age 15)',
 'Mortality between Age 15 and 60, both sexes (deaths under age 60 per 1,000 alive at age 15)',
 'Male Mortality between Age 15 and 60 (deaths under age 60 per 1,000 males alive at age 15)',
 'Female Mortality between Age 15 and 60 (deaths under age 60 per 1,000 females alive at age 15)',
 'Net Number of Migrants (thousands)']

In [17]:
for column in column_contained_space:
    data[column] = (data[column].astype(str).str.replace(r"\s+","",regex=True)) # astype(str) convert the data into string, Regex = True means it is regular expression not plain text. 
    data[column] = pd.to_numeric(data[column], errors = 'coerce')

In [9]:
# check every column data
data.iloc[0].T

15
Variant                                                                                            Estimates
Region, subregion, country or area *                                                                   World
Location code                                                                                            900
ISO3 Alpha-code                                                                                          NaN
Type                                                                                                   World
Year                                                                                                    1950
Total Population, as of 1 January (thousands)                                                        2471424
Total Population, as of 1 July (thousands)                                                           2493093
Male Population, as of 1 July (thousands)                                                            1241432
Female Population, as of 1 July (thousands)                                                          1251661
Population Density, as of 1 July (persons per square km)                                                19.1
Population Sex Ratio, as of 1 July (males per 100 females)                                              99.2
Median Age, as of 1 July (years)                                                                        22.2
Natural Change, Births minus Deaths (thousands)                                                        43337
Rate of Natural Change (per 1,000 population)                                                           17.4
Population Change (thousands)                                                                          43338
Population Growth Rate (percentage)                                                                     1.74
Population Annual Doubling Time (years)                                                                 39.9
Births (thousands)                                                                                     91824
Births by women aged 15 to 19 (thousands)                                                              10492
Crude Birth Rate (births per 1,000 population)                                                          36.8
Total Fertility Rate (live births per woman)                                                            4.85
Net Reproduction Rate (surviving daughters per woman)                                                   1.63
Mean Age Childbearing (years)                                                                           28.9
Sex Ratio at Birth (males per 100 female births)                                                         105
Total Deaths (thousands)                                                                               48487
Male Deaths (thousands)                                                                                25664
Female Deaths (thousands)                                                                              22823
Crude Death Rate (deaths per 1,000 population)                                                          19.4
Life Expectancy at Birth, both sexes (years)                                                            46.4
Male Life Expectancy at Birth (years)                                                                   44.5
Female Life Expectancy at Birth (years)                                                                 48.4
Life Expectancy at Age 15, both sexes (years)                                                           47.2
Male Life Expectancy at Age 15 (years)                                                                  45.0
Female Life Expectancy at Age 15 (years)                                                                49.5
Life Expectancy at Age 65, both sexes (years)                                                           11.4
Male Life Expectancy at Age 65 (years)                                                                  10.5
Female Life Expectancy at Age 65 (years)                                                                12.1
Life Expectancy at Age 80, both sexes (years)                                                            5.1
Male Life Expectancy at Age 80 (years)                                                                   4.8
Female Life Expectancy at Age 80 (years)                                                                 5.3
Infant Deaths, under age 1 (thousands)                                                                 12546
Infant Mortality Rate (infant deaths per 1,000 live births)                                            138.1
Live Births Surviving to Age 1 (thousands)                                                        82,937.226
Under-Five Deaths, under age 5 (thousands)                                                             19962
Under-Five Mortality (deaths under age 5 per 1,000 live births)                                          227
Mortality before Age 40, both sexes (deaths under age 40 per 1,000 live births)                          374
Male Mortality before Age 40 (deaths under age 40 per 1,000 male live births)                            391
Female Mortality before Age 40 (deaths under age 40 per 1,000 female live births)                        356
Mortality before Age 60, both sexes (deaths under age 60 per 1,000 live births)                          540
Male Mortality before Age 60 (deaths under age 60 per 1,000 male live births)                            581
Female Mortality before Age 60 (deaths under age 60 per 1,000 female live births)                        497
Mortality between Age 15 and 50, both sexes (deaths under age 50 per 1,000 alive at age 15)              239
Male Mortality between Age 15 and 50 (deaths under age 50 per 1,000 males alive at age 15)               269
Female Mortality between Age 15 and 50 (deaths under age 50 per 1,000 females alive at age 15)           208
Mortality between Age 15 and 60, both sexes (deaths under age 60 per 1,000 alive at age 15)              375
Male Mortality between Age 15 and 60 (deaths under age 60 per 1,000 males alive at age 15)               426
Female Mortality between Age 15 and 60 (deaths under age 60 per 1,000 females alive at age 15)           323
Net Number of Migrants (thousands)                                                                         0
Net Migration Rate (per 1,000 population)                                                                  0
Name: 0, dtype: object

In [18]:
# we can see only one column 'Live Births Surviving to Age 1 (thousands)' contian ',' we should remove it
data['Live Births Surviving to Age 1 (thousands)'] = data['Live Births Surviving to Age 1 (thousands)'].astype(str).str.replace(r",","",regex=True)
data['Live Births Surviving to Age 1 (thousands)'] = pd.to_numeric(data['Live Births Surviving to Age 1 (thousands)'], errors='coerce')

In [19]:
data.iloc[0].T

15
Variant                                                                                           Estimates
Region, subregion, country or area *                                                                  World
Location code                                                                                           900
ISO3 Alpha-code                                                                                         NaN
Type                                                                                                  World
Year                                                                                                   1950
Total Population, as of 1 January (thousands)                                                       2471424
Total Population, as of 1 July (thousands)                                                          2493093
Male Population, as of 1 July (thousands)                                                           1241432
Female Population, as of 1 July (thousands)                                                         1251661
Population Density, as of 1 July (persons per square km)                                               19.1
Population Sex Ratio, as of 1 July (males per 100 females)                                             99.2
Median Age, as of 1 July (years)                                                                       22.2
Natural Change, Births minus Deaths (thousands)                                                       43337
Rate of Natural Change (per 1,000 population)                                                          17.4
Population Change (thousands)                                                                         43338
Population Growth Rate (percentage)                                                                    1.74
Population Annual Doubling Time (years)                                                                39.9
Births (thousands)                                                                                    91824
Births by women aged 15 to 19 (thousands)                                                             10492
Crude Birth Rate (births per 1,000 population)                                                         36.8
Total Fertility Rate (live births per woman)                                                           4.85
Net Reproduction Rate (surviving daughters per woman)                                                  1.63
Mean Age Childbearing (years)                                                                          28.9
Sex Ratio at Birth (males per 100 female births)                                                        105
Total Deaths (thousands)                                                                              48487
Male Deaths (thousands)                                                                               25664
Female Deaths (thousands)                                                                             22823
Crude Death Rate (deaths per 1,000 population)                                                         19.4
Life Expectancy at Birth, both sexes (years)                                                           46.4
Male Life Expectancy at Birth (years)                                                                  44.5
Female Life Expectancy at Birth (years)                                                                48.4
Life Expectancy at Age 15, both sexes (years)                                                          47.2
Male Life Expectancy at Age 15 (years)                                                                 45.0
Female Life Expectancy at Age 15 (years)                                                               49.5
Life Expectancy at Age 65, both sexes (years)                                                          11.4
Male Life Expectancy at Age 65 (years)                                                                 10.5
Female Life Expectancy at Age 65 (years)                                                               12.1
Life Expectancy at Age 80, both sexes (years)                                                           5.1
Male Life Expectancy at Age 80 (years)                                                                  4.8
Female Life Expectancy at Age 80 (years)                                                                5.3
Infant Deaths, under age 1 (thousands)                                                                12546
Infant Mortality Rate (infant deaths per 1,000 live births)                                           138.1
Live Births Surviving to Age 1 (thousands)                                                        82937.226
Under-Five Deaths, under age 5 (thousands)                                                            19962
Under-Five Mortality (deaths under age 5 per 1,000 live births)                                         227
Mortality before Age 40, both sexes (deaths under age 40 per 1,000 live births)                         374
Male Mortality before Age 40 (deaths under age 40 per 1,000 male live births)                           391
Female Mortality before Age 40 (deaths under age 40 per 1,000 female live births)                       356
Mortality before Age 60, both sexes (deaths under age 60 per 1,000 live births)                         540
Male Mortality before Age 60 (deaths under age 60 per 1,000 male live births)                           581
Female Mortality before Age 60 (deaths under age 60 per 1,000 female live births)                       497
Mortality between Age 15 and 50, both sexes (deaths under age 50 per 1,000 alive at age 15)             239
Male Mortality between Age 15 and 50 (deaths under age 50 per 1,000 males alive at age 15)              269
Female Mortality between Age 15 and 50 (deaths under age 50 per 1,000 females alive at age 15)          208
Mortality between Age 15 and 60, both sexes (deaths under age 60 per 1,000 alive at age 15)             375
Male Mortality between Age 15 and 60 (deaths under age 60 per 1,000 males alive at age 15)              426
Female Mortality between Age 15 and 60 (deaths under age 60 per 1,000 females alive at age 15)          323
Net Number of Migrants (thousands)                                                                        0
Net Migration Rate (per 1,000 population)                                                                 0
Name: 0, dtype: object

In [20]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 222 entries, 0 to 221
Data columns (total 60 columns):
 #   Column                                                                                          Non-Null Count  Dtype
---  ------                                                                                          --------------  -----
 0   Variant                                                                                         222 non-null    str
 1   Region, subregion, country or area *                                                            222 non-null    str
 2   Location code                                                                                   222 non-null    object
 3   ISO3 Alpha-code                                                                                 148 non-null    str
 4   Type                                                                                            222 non-null    str
 5   Year                                                                                            222 non-null    object
 6   Total Population, as of 1 January (thousands)                                                   222 non-null    int64
 7   Total Population, as of 1 July (thousands)                                                      222 non-null    int64
 8   Male Population, as of 1 July (thousands)                                                       222 non-null    int64
 9   Female Population, as of 1 July (thousands)                                                     222 non-null    int64
 10  Population Density, as of 1 July (persons per square km)                                        222 non-null    object
 11  Population Sex Ratio, as of 1 July (males per 100 females)                                      222 non-null    object
 12  Median Age, as of 1 July (years)                                                                222 non-null    object
 13  Natural Change, Births minus Deaths (thousands)                                                 222 non-null    int64
 14  Rate of Natural Change (per 1,000 population)                                                   222 non-null    object
 15  Population Change (thousands)                                                                   222 non-null    int64
 16  Population Growth Rate (percentage)                                                             222 non-null    object
 17  Population Annual Doubling Time (years)                                                         222 non-null    str
 18  Births (thousands)                                                                              222 non-null    int64
 19  Births by women aged 15 to 19 (thousands)                                                       222 non-null    int64
 20  Crude Birth Rate (births per 1,000 population)                                                  222 non-null    object
 21  Total Fertility Rate (live births per woman)                                                    222 non-null    object
 22  Net Reproduction Rate (surviving daughters per woman)                                           222 non-null    object
 23  Mean Age Childbearing (years)                                                                   222 non-null    object
 24  Sex Ratio at Birth (males per 100 female births)                                                222 non-null    int64
 25  Total Deaths (thousands)                                                                        222 non-null    int64
 26  Male Deaths (thousands)                                                                         222 non-null    int64
 27  Female Deaths (thousands)                                                                       222 non-null    int64
 28  Crude Death Rate (deaths per 1,000 population)                                                  222 non-null    object
 29  Life Expectancy at Birth, both sexes (years)                                                    222 non-null    object
 30  Male Life Expectancy at Birth (years)                                                           222 non-null    object
 31  Female Life Expectancy at Birth (years)                                                         222 non-null    object
 32  Life Expectancy at Age 15, both sexes (years)                                                   222 non-null    object
 33  Male Life Expectancy at Age 15 (years)                                                          222 non-null    object
 34  Female Life Expectancy at Age 15 (years)                                                        222 non-null    object
 35  Life Expectancy at Age 65, both sexes (years)                                                   222 non-null    object
 36  Male Life Expectancy at Age 65 (years)                                                          222 non-null    object
 37  Female Life Expectancy at Age 65 (years)                                                        222 non-null    object
 38  Life Expectancy at Age 80, both sexes (years)                                                   222 non-null    object
 39  Male Life Expectancy at Age 80 (years)                                                          222 non-null    object
 40  Female Life Expectancy at Age 80 (years)                                                        222 non-null    object
 41  Infant Deaths, under age 1 (thousands)                                                          222 non-null    int64
 42  Infant Mortality Rate (infant deaths per 1,000 live births)                                     222 non-null    object
 43  Live Births Surviving to Age 1 (thousands)                                                      222 non-null    float64
 44  Under-Five Deaths, under age 5 (thousands)                                                      222 non-null    int64
 45  Under-Five Mortality (deaths under age 5 per 1,000 live births)                                 222 non-null    int64
 46  Mortality before Age 40, both sexes (deaths under age 40 per 1,000 live births)                 222 non-null    int64
 47  Male Mortality before Age 40 (deaths under age 40 per 1,000 male live births)                   222 non-null    int64
 48  Female Mortality before Age 40 (deaths under age 40 per 1,000 female live births)               222 non-null    int64
 49  Mortality before Age 60, both sexes (deaths under age 60 per 1,000 live births)                 222 non-null    int64
 50  Male Mortality before Age 60 (deaths under age 60 per 1,000 male live births)                   222 non-null    int64
 51  Female Mortality before Age 60 (deaths under age 60 per 1,000 female live births)               222 non-null    int64
 52  Mortality between Age 15 and 50, both sexes (deaths under age 50 per 1,000 alive at age 15)     222 non-null    int64
 53  Male Mortality between Age 15 and 50 (deaths under age 50 per 1,000 males alive at age 15)      222 non-null    int64
 54  Female Mortality between Age 15 and 50 (deaths under age 50 per 1,000 females alive at age 15)  222 non-null    int64
 55  Mortality between Age 15 and 60, both sexes (deaths under age 60 per 1,000 alive at age 15)     222 non-null    int64
 56  Male Mortality between Age 15 and 60 (deaths under age 60 per 1,000 males alive at age 15)      222 non-null    int64
 57  Female Mortality between Age 15 and 60 (deaths under age 60 per 1,000 females alive at age 15)  222 non-null    int64
 58  Net Number of Migrants (thousands)                                                              222 non-null    int64
 59  Net Migration Rate (per 1,000 population)                                                       222 non-null    object
dtypes: float64(1), int64(28), object(26), str(5)
memory usage: 104.2+ KB

In [21]:
# I donot want to convert column variant, region subregion, country or area * , location code, IS0# Alpha-code, Type
numeric_data = data.columns.difference(['Variant','Region, subregion, country or area *','ISO3 Alpha-code','Type'])
data[numeric_data] = data[numeric_data].apply(pd.to_numeric, errors='coerce')

In [14]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 222 entries, 0 to 221
Data columns (total 60 columns):
 #   Column                                                                                          Non-Null Count  Dtype
---  ------                                                                                          --------------  -----
 0   Variant                                                                                         222 non-null    str
 1   Region, subregion, country or area *                                                            222 non-null    str
 2   Location code                                                                                   222 non-null    int64
 3   ISO3 Alpha-code                                                                                 148 non-null    str
 4   Type                                                                                            222 non-null    str
 5   Year                                                                                            222 non-null    float64
 6   Total Population, as of 1 January (thousands)                                                   222 non-null    int64
 7   Total Population, as of 1 July (thousands)                                                      222 non-null    int64
 8   Male Population, as of 1 July (thousands)                                                       222 non-null    int64
 9   Female Population, as of 1 July (thousands)                                                     222 non-null    int64
 10  Population Density, as of 1 July (persons per square km)                                        222 non-null    float64
 11  Population Sex Ratio, as of 1 July (males per 100 females)                                      222 non-null    float64
 12  Median Age, as of 1 July (years)                                                                222 non-null    float64
 13  Natural Change, Births minus Deaths (thousands)                                                 222 non-null    int64
 14  Rate of Natural Change (per 1,000 population)                                                   222 non-null    float64
 15  Population Change (thousands)                                                                   222 non-null    int64
 16  Population Growth Rate (percentage)                                                             222 non-null    float64
 17  Population Annual Doubling Time (years)                                                         214 non-null    float64
 18  Births (thousands)                                                                              222 non-null    int64
 19  Births by women aged 15 to 19 (thousands)                                                       222 non-null    int64
 20  Crude Birth Rate (births per 1,000 population)                                                  222 non-null    float64
 21  Total Fertility Rate (live births per woman)                                                    222 non-null    float64
 22  Net Reproduction Rate (surviving daughters per woman)                                           222 non-null    float64
 23  Mean Age Childbearing (years)                                                                   222 non-null    float64
 24  Sex Ratio at Birth (males per 100 female births)                                                222 non-null    int64
 25  Total Deaths (thousands)                                                                        222 non-null    int64
 26  Male Deaths (thousands)                                                                         222 non-null    int64
 27  Female Deaths (thousands)                                                                       222 non-null    int64
 28  Crude Death Rate (deaths per 1,000 population)                                                  222 non-null    float64
 29  Life Expectancy at Birth, both sexes (years)                                                    222 non-null    float64
 30  Male Life Expectancy at Birth (years)                                                           222 non-null    float64
 31  Female Life Expectancy at Birth (years)                                                         222 non-null    float64
 32  Life Expectancy at Age 15, both sexes (years)                                                   222 non-null    float64
 33  Male Life Expectancy at Age 15 (years)                                                          222 non-null    float64
 34  Female Life Expectancy at Age 15 (years)                                                        222 non-null    float64
 35  Life Expectancy at Age 65, both sexes (years)                                                   222 non-null    float64
 36  Male Life Expectancy at Age 65 (years)                                                          222 non-null    float64
 37  Female Life Expectancy at Age 65 (years)                                                        222 non-null    float64
 38  Life Expectancy at Age 80, both sexes (years)                                                   222 non-null    float64
 39  Male Life Expectancy at Age 80 (years)                                                          222 non-null    float64
 40  Female Life Expectancy at Age 80 (years)                                                        222 non-null    float64
 41  Infant Deaths, under age 1 (thousands)                                                          222 non-null    int64
 42  Infant Mortality Rate (infant deaths per 1,000 live births)                                     222 non-null    float64
 43  Live Births Surviving to Age 1 (thousands)                                                      222 non-null    float64
 44  Under-Five Deaths, under age 5 (thousands)                                                      222 non-null    int64
 45  Under-Five Mortality (deaths under age 5 per 1,000 live births)                                 222 non-null    int64
 46  Mortality before Age 40, both sexes (deaths under age 40 per 1,000 live births)                 222 non-null    int64
 47  Male Mortality before Age 40 (deaths under age 40 per 1,000 male live births)                   222 non-null    int64
 48  Female Mortality before Age 40 (deaths under age 40 per 1,000 female live births)               222 non-null    int64
 49  Mortality before Age 60, both sexes (deaths under age 60 per 1,000 live births)                 222 non-null    int64
 50  Male Mortality before Age 60 (deaths under age 60 per 1,000 male live births)                   222 non-null    int64
 51  Female Mortality before Age 60 (deaths under age 60 per 1,000 female live births)               222 non-null    int64
 52  Mortality between Age 15 and 50, both sexes (deaths under age 50 per 1,000 alive at age 15)     222 non-null    int64
 53  Male Mortality between Age 15 and 50 (deaths under age 50 per 1,000 males alive at age 15)      222 non-null    int64
 54  Female Mortality between Age 15 and 50 (deaths under age 50 per 1,000 females alive at age 15)  222 non-null    int64
 55  Mortality between Age 15 and 60, both sexes (deaths under age 60 per 1,000 alive at age 15)     222 non-null    int64
 56  Male Mortality between Age 15 and 60 (deaths under age 60 per 1,000 males alive at age 15)      222 non-null    int64
 57  Female Mortality between Age 15 and 60 (deaths under age 60 per 1,000 females alive at age 15)  222 non-null    int64
 58  Net Number of Migrants (thousands)                                                              222 non-null    int64
 59  Net Migration Rate (per 1,000 population)                                                       222 non-null    float64
dtypes: float64(27), int64(29), str(4)
memory usage: 104.2 KB

In [22]:
data.columns

Index(['Variant', 'Region, subregion, country or area *', 'Location code',
       'ISO3 Alpha-code', 'Type', 'Year',
       'Total Population, as of 1 January (thousands)',
       'Total Population, as of 1 July (thousands)',
       'Male Population, as of 1 July (thousands)',
       'Female Population, as of 1 July (thousands)',
       'Population Density, as of 1 July (persons per square km)',
       'Population Sex Ratio, as of 1 July (males per 100 females)',
       'Median Age, as of 1 July (years)',
       'Natural Change, Births minus Deaths (thousands)',
       'Rate of Natural Change (per 1,000 population)',
       'Population Change (thousands)', 'Population Growth Rate (percentage)',
       'Population Annual Doubling Time (years)', 'Births (thousands)',
       'Births by women aged 15 to 19 (thousands)',
       'Crude Birth Rate (births per 1,000 population)',
       'Total Fertility Rate (live births per woman)',
       'Net Reproduction Rate (surviving daughters per woman)',
       'Mean Age Childbearing (years)',
       'Sex Ratio at Birth (males per 100 female births)',
       'Total Deaths (thousands)', 'Male Deaths (thousands)',
       'Female Deaths (thousands)',
       'Crude Death Rate (deaths per 1,000 population)',
       'Life Expectancy at Birth, both sexes (years)',
       'Male Life Expectancy at Birth (years)',
       'Female Life Expectancy at Birth (years)',
       'Life Expectancy at Age 15, both sexes (years)',
       'Male Life Expectancy at Age 15 (years)',
       'Female Life Expectancy at Age 15 (years)',
       'Life Expectancy at Age 65, both sexes (years)',
       'Male Life Expectancy at Age 65 (years)',
       'Female Life Expectancy at Age 65 (years)',
       'Life Expectancy at Age 80, both sexes (years)',
       'Male Life Expectancy at Age 80 (years)',
       'Female Life Expectancy at Age 80 (years)',
       'Infant Deaths, under age 1 (thousands)',
       'Infant Mortality Rate (infant deaths per 1,000 live births)',
       'Live Births Surviving to Age 1 (thousands)',
       'Under-Five Deaths, under age 5 (thousands)',
       'Under-Five Mortality (deaths under age 5 per 1,000 live births)',
       'Mortality before Age 40, both sexes (deaths under age 40 per 1,000 live births)',
       'Male Mortality before Age 40 (deaths under age 40 per 1,000 male live births)',
       'Female Mortality before Age 40 (deaths under age 40 per 1,000 female live births)',
       'Mortality before Age 60, both sexes (deaths under age 60 per 1,000 live births)',
       'Male Mortality before Age 60 (deaths under age 60 per 1,000 male live births)',
       'Female Mortality before Age 60 (deaths under age 60 per 1,000 female live births)',
       'Mortality between Age 15 and 50, both sexes (deaths under age 50 per 1,000 alive at age 15)',
       'Male Mortality between Age 15 and 50 (deaths under age 50 per 1,000 males alive at age 15)',
       'Female Mortality between Age 15 and 50 (deaths under age 50 per 1,000 females alive at age 15)',
       'Mortality between Age 15 and 60, both sexes (deaths under age 60 per 1,000 alive at age 15)',
       'Male Mortality between Age 15 and 60 (deaths under age 60 per 1,000 males alive at age 15)',
       'Female Mortality between Age 15 and 60 (deaths under age 60 per 1,000 females alive at age 15)',
       'Net Number of Migrants (thousands)',
       'Net Migration Rate (per 1,000 population)'],
      dtype='object', name=15)

In [23]:
Base_data = data[['Variant', 'Region, subregion, country or area *','Location code', 'ISO3 Alpha-code','Type', 'Year']]
Base_data

15,Variant,"Region, subregion, country or area *",Location code,ISO3 Alpha-code,Type,Year
0,Estimates,World,900,NaN,World,1950.0
1,Estimates,World,900,NaN,World,1951.0
2,Estimates,World,900,NaN,World,1952.0
3,Estimates,World,900,NaN,World,1953.0
4,Estimates,World,900,NaN,World,1954.0
...,...,...,...,...,...,...
217,Estimates,India,356,IND,Country/Area,2019.0
218,Estimates,India,356,IND,Country/Area,2020.0
219,Estimates,India,356,IND,Country/Area,2021.0
220,Estimates,India,356,IND,Country/Area,2022.0
221,Estimates,India,356,IND,Country/Area,2023.0

In [24]:
Population_data = data[['Total Population, as of 1 January (thousands)','Total Population, as of 1 July (thousands)',
       'Male Population, as of 1 July (thousands)',
       'Female Population, as of 1 July (thousands)',
       'Population Density, as of 1 July (persons per square km)',
       'Population Sex Ratio, as of 1 July (males per 100 females)',
       'Median Age, as of 1 July (years)',
       'Natural Change, Births minus Deaths (thousands)',
       'Rate of Natural Change (per 1,000 population)',
       'Population Change (thousands)', 'Population Growth Rate (percentage)',
       'Population Annual Doubling Time (years)']]
Population_data

15,"Total Population, as of 1 January (thousands)","Total Population, as of 1 July (thousands)","Male Population, as of 1 July (thousands)","Female Population, as of 1 July (thousands)","Population Density, as of 1 July (persons per square km)","Population Sex Ratio, as of 1 July (males per 100 females)","Median Age, as of 1 July (years)","Natural Change, Births minus Deaths (thousands)","Rate of Natural Change (per 1,000 population)",Population Change (thousands),Population Growth Rate (percentage),Population Annual Doubling Time (years)
0,2471424,2493093,1241432,1251661,19.1,99.2,22.2,43337,17.4,43338,1.74,39.9
1,2514762,2536927,1263362,1273565,19.5,99.2,22.1,44331,17.5,44331,1.75,39.7
2,2559092,2584086,1287093,1296993,19.8,99.2,22.1,49988,19.3,49988,1.94,35.8
3,2609080,2634106,1312355,1321751,20.2,99.3,22.0,50052,19.0,50052,1.90,36.5
4,2659132,2685895,1338531,1347364,20.6,99.3,21.9,53525,19.9,53525,1.99,34.8
...,...,...,...,...,...,...,...,...,...,...,...,...
217,1382090,1389030,717351,671679,467.2,106.8,26.7,14861,10.7,13882,1.00,69.4
218,1395971,1402618,724175,678442,471.8,106.7,27.0,13367,9.5,13293,0.95,73.1
219,1409264,1414204,729924,684280,475.7,106.7,27.3,10228,7.2,9879,0.70,99.2
220,1419143,1425423,735531,689892,479.4,106.6,27.7,13913,9.8,12559,0.88,78.7
221,1431703,1438070,741883,696186,483.7,106.6,28.1,13712,9.5,12733,0.89,78.3

In [25]:
Fertility_data = data[['Births (thousands)',
       'Births by women aged 15 to 19 (thousands)',
       'Crude Birth Rate (births per 1,000 population)',
       'Total Fertility Rate (live births per woman)',
       'Net Reproduction Rate (surviving daughters per woman)',
       'Mean Age Childbearing (years)',
       'Sex Ratio at Birth (males per 100 female births)']]
Fertility_data

15,Births (thousands),Births by women aged 15 to 19 (thousands),"Crude Birth Rate (births per 1,000 population)",Total Fertility Rate (live births per woman),Net Reproduction Rate (surviving daughters per woman),Mean Age Childbearing (years),Sex Ratio at Birth (males per 100 female births)
0,91824,10492,36.8,4.85,1.63,28.9,105
1,92507,10574,36.5,4.82,1.64,28.9,105
2,97371,11034,37.7,5.00,1.73,28.9,105
3,97291,11045,36.9,4.92,1.71,28.9,105
4,100188,11302,37.3,5.00,1.76,28.9,105
...,...,...,...,...,...,...,...
217,24125,924,17.4,2.12,0.97,27.5,108
218,23485,900,16.7,2.05,0.94,27.5,108
219,23322,887,16.5,2.01,0.93,27.5,108
220,23286,874,16.3,1.99,0.92,27.5,108
221,23219,859,16.1,1.98,0.92,27.5,107

In [19]:
Mortality_data = data[['Total Deaths (thousands)', 'Male Deaths (thousands)',
       'Female Deaths (thousands)',
       'Crude Death Rate (deaths per 1,000 population)',
       'Life Expectancy at Birth, both sexes (years)',
       'Male Life Expectancy at Birth (years)',
       'Female Life Expectancy at Birth (years)',
       'Life Expectancy at Age 15, both sexes (years)',
       'Male Life Expectancy at Age 15 (years)',
       'Female Life Expectancy at Age 15 (years)',
       'Life Expectancy at Age 65, both sexes (years)',
       'Male Life Expectancy at Age 65 (years)',
       'Female Life Expectancy at Age 65 (years)',
       'Life Expectancy at Age 80, both sexes (years)',
       'Male Life Expectancy at Age 80 (years)',
       'Female Life Expectancy at Age 80 (years)',
       'Infant Deaths, under age 1 (thousands)',
       'Infant Mortality Rate (infant deaths per 1,000 live births)',
       'Live Births Surviving to Age 1 (thousands)',
       'Under-Five Deaths, under age 5 (thousands)',
       'Under-Five Mortality (deaths under age 5 per 1,000 live births)',
       'Mortality before Age 40, both sexes (deaths under age 40 per 1,000 live births)',
       'Male Mortality before Age 40 (deaths under age 40 per 1,000 male live births)',
       'Female Mortality before Age 40 (deaths under age 40 per 1,000 female live births)',
       'Mortality before Age 60, both sexes (deaths under age 60 per 1,000 live births)',
       'Male Mortality before Age 60 (deaths under age 60 per 1,000 male live births)',
       'Female Mortality before Age 60 (deaths under age 60 per 1,000 female live births)',
       'Mortality between Age 15 and 50, both sexes (deaths under age 50 per 1,000 alive at age 15)',
       'Male Mortality between Age 15 and 50 (deaths under age 50 per 1,000 males alive at age 15)',
       'Female Mortality between Age 15 and 50 (deaths under age 50 per 1,000 females alive at age 15)',
       'Mortality between Age 15 and 60, both sexes (deaths under age 60 per 1,000 alive at age 15)',
       'Male Mortality between Age 15 and 60 (deaths under age 60 per 1,000 males alive at age 15)',
       'Female Mortality between Age 15 and 60 (deaths under age 60 per 1,000 females alive at age 15)']]
Mortality_data

15,Total Deaths (thousands),Male Deaths (thousands),Female Deaths (thousands),"Crude Death Rate (deaths per 1,000 population)","Life Expectancy at Birth, both sexes (years)",Male Life Expectancy at Birth (years),Female Life Expectancy at Birth (years),"Life Expectancy at Age 15, both sexes (years)",Male Life Expectancy at Age 15 (years),Female Life Expectancy at Age 15 (years),...,"Female Mortality before Age 40 (deaths under age 40 per 1,000 female live births)","Mortality before Age 60, both sexes (deaths under age 60 per 1,000 live births)","Male Mortality before Age 60 (deaths under age 60 per 1,000 male live births)","Female Mortality before Age 60 (deaths under age 60 per 1,000 female live births)","Mortality between Age 15 and 50, both sexes (deaths under age 50 per 1,000 alive at age 15)","Male Mortality between Age 15 and 50 (deaths under age 50 per 1,000 males alive at age 15)","Female Mortality between Age 15 and 50 (deaths under age 50 per 1,000 females alive at age 15)","Mortality between Age 15 and 60, both sexes (deaths under age 60 per 1,000 alive at age 15)","Male Mortality between Age 15 and 60 (deaths under age 60 per 1,000 males alive at age 15)","Female Mortality between Age 15 and 60 (deaths under age 60 per 1,000 females alive at age 15)"
0,48487,25664,22823,19.4,46.4,44.5,48.4,47.2,45.0,49.5,...,356,540,581,497,239,269,208,375,426,323
1,48176,25384,22792,19.0,47.1,45.3,49.0,47.6,45.6,49.8,...,348,528,567,488,230,256,203,365,413,316
2,47383,24850,22533,18.3,48.2,46.5,50.0,48.4,46.5,50.3,...,337,511,546,475,217,239,196,351,393,307
3,47240,24722,22518,17.9,48.8,47.2,50.5,48.7,46.9,50.5,...,330,502,536,467,211,231,191,343,384,301
4,46662,24408,22254,17.4,49.7,48.0,51.3,49.2,47.5,51.0,...,320,489,522,456,203,221,185,332,372,293
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,9264,5001,4263,6.7,70.7,69.3,72.3,58.6,57.1,60.2,...,66,197,223,170,73,89,56,164,191,135
218,10118,5550,4569,7.2,70.2,68.5,71.9,57.8,56.1,59.7,...,62,202,229,172,71,87,55,171,200,139
219,13094,7025,6069,9.3,67.3,65.9,68.8,54.7,53.2,56.3,...,66,247,278,213,92,111,72,220,252,184
220,9373,5066,4307,6.6,71.7,70.2,73.3,59.1,57.6,60.8,...,57,183,208,155,67,82,50,154,181,126
221,9507,5145,4362,6.6,72.0,70.5,73.6,59.3,57.8,60.9,...,54,178,204,150,65,80,49,151,178,122

In [41]:
Migration_data = data[['Net Number of Migrants (thousands)',
       'Net Migration Rate (per 1,000 population)']]
Migration_data

15,Net Number of Migrants (thousands),"Net Migration Rate (per 1,000 population)"
0,0,0.0
1,0,0.0
2,0,0.0
3,0,0.0
4,0,0.0
...,...,...
217,-979,-0.7
218,-74,-0.1
219,-349,-0.2
220,-1353,-1.0
221,-979,-0.7

Dataframe to CSV

In [21]:
Base_data.isnull().sum()

15
Variant                                  0
Region, subregion, country or area *     0
Location code                            0
ISO3 Alpha-code                         74
Type                                     0
Year                                     0
dtype: int64

In [22]:
Population_data.isnull().sum()

15
Total Population, as of 1 January (thousands)                 0
Total Population, as of 1 July (thousands)                    0
Male Population, as of 1 July (thousands)                     0
Female Population, as of 1 July (thousands)                   0
Population Density, as of 1 July (persons per square km)      0
Population Sex Ratio, as of 1 July (males per 100 females)    0
Median Age, as of 1 July (years)                              0
Natural Change, Births minus Deaths (thousands)               0
Rate of Natural Change (per 1,000 population)                 0
Population Change (thousands)                                 0
Population Growth Rate (percentage)                           0
Population Annual Doubling Time (years)                       8
dtype: int64

In [23]:
Fertility_data.isnull().sum()

15
Births (thousands)                                       0
Births by women aged 15 to 19 (thousands)                0
Crude Birth Rate (births per 1,000 population)           0
Total Fertility Rate (live births per woman)             0
Net Reproduction Rate (surviving daughters per woman)    0
Mean Age Childbearing (years)                            0
Sex Ratio at Birth (males per 100 female births)         0
dtype: int64

In [24]:
Mortality_data.isnull().sum()

15
Total Deaths (thousands)                                                                          0
Male Deaths (thousands)                                                                           0
Female Deaths (thousands)                                                                         0
Crude Death Rate (deaths per 1,000 population)                                                    0
Life Expectancy at Birth, both sexes (years)                                                      0
Male Life Expectancy at Birth (years)                                                             0
Female Life Expectancy at Birth (years)                                                           0
Life Expectancy at Age 15, both sexes (years)                                                     0
Male Life Expectancy at Age 15 (years)                                                            0
Female Life Expectancy at Age 15 (years)                                                          0
Life Expectancy at Age 65, both sexes (years)                                                     0
Male Life Expectancy at Age 65 (years)                                                            0
Female Life Expectancy at Age 65 (years)                                                          0
Life Expectancy at Age 80, both sexes (years)                                                     0
Male Life Expectancy at Age 80 (years)                                                            0
Female Life Expectancy at Age 80 (years)                                                          0
Infant Deaths, under age 1 (thousands)                                                            0
Infant Mortality Rate (infant deaths per 1,000 live births)                                       0
Live Births Surviving to Age 1 (thousands)                                                        0
Under-Five Deaths, under age 5 (thousands)                                                        0
Under-Five Mortality (deaths under age 5 per 1,000 live births)                                   0
Mortality before Age 40, both sexes (deaths under age 40 per 1,000 live births)                   0
Male Mortality before Age 40 (deaths under age 40 per 1,000 male live births)                     0
Female Mortality before Age 40 (deaths under age 40 per 1,000 female live births)                 0
Mortality before Age 60, both sexes (deaths under age 60 per 1,000 live births)                   0
Male Mortality before Age 60 (deaths under age 60 per 1,000 male live births)                     0
Female Mortality before Age 60 (deaths under age 60 per 1,000 female live births)                 0
Mortality between Age 15 and 50, both sexes (deaths under age 50 per 1,000 alive at age 15)       0
Male Mortality between Age 15 and 50 (deaths under age 50 per 1,000 males alive at age 15)        0
Female Mortality between Age 15 and 50 (deaths under age 50 per 1,000 females alive at age 15)    0
Mortality between Age 15 and 60, both sexes (deaths under age 60 per 1,000 alive at age 15)       0
Male Mortality between Age 15 and 60 (deaths under age 60 per 1,000 males alive at age 15)        0
Female Mortality between Age 15 and 60 (deaths under age 60 per 1,000 females alive at age 15)    0
dtype: int64

In [25]:
Migration_data.isnull().sum()

15
Net Number of Migrants (thousands)           0
Net Migration Rate (per 1,000 population)    0
dtype: int64

In [26]:
import sys
from pathlib import Path

project_root = Path.cwd().parent
# cwd() -> gets current file path
# .parent -> moves to the parent folder (WORLD DEMOCRATIC INDEX)
# Store this parent path as an object.

if str(project_root) not in sys.path:
    # sys.path is the directory where Python looks for modules.
    sys.path.insert(0, str(project_root))
    # If the project root path is not in Python's search path, add it at index 0.

In [162]:
import json
from collections import defaultdict
def checking_duplicates(column_metadata):
    grouped_duplicates = defaultdict(list)
    for keys, values in column_metadata.items():
        grouped_duplicates[values['name']].append(keys)

    duplicates = {val: key for val, key in grouped_duplicates.items() if len(key) > 1}
    print (duplicates)

def save_metadata(variables, output_dir):
    with open(output_dir / "metadata.json", "w", encoding="utf-8") as file:
       # json.dump(variables, file, indent=4)
       pass
# check the metadata.json file

In [ ]:
# metadata generator it create abbriviations of each column by concatenating first letter of every words of every columns.
import re
match = r'15|19|40|50|60|65|80'

data_table = [Base_data, Population_data, Fertility_data, Mortality_data, Migration_data]
data_name = ['Base_data', 'Population_data', 'Fertility_data', 'Mortality_data', 'Migration_data']
output_dir = Path.cwd().parent / "utils"
STOP_WORDS = {
    "of", "the", "a", "an",
    "as", "at", "to", "on", "in",
    "and", "or", "by", "for",
    "with", "per", "both",
    "before", "between", "under",
    "minus", "about"
}
STOP_NUMBERS = {'1', '000'}

all_metadata = {}
for data_,name_ in zip(data_table,data_name):
    col_umn = data_.columns.to_list()

    column_metadata = {}
    for col in col_umn:
        # checking first 3 words and extract first letter of word and make separate string
        split_text = re.findall(r"[^()]+", col)
        word_ = re.findall(r"[a-zA-Z0-9]+", split_text[0])
        word_ = [word for word in word_ if word.lower() not in STOP_WORDS]

        string_T = ""
        if len(word_) == 1:
            string_T = str(word_[0]).upper()
        else:
            for i in range(0,3):
                if 0 <= i < len(word_):
                    letter_i = list(word_[i].upper())
                    string_T += f"{letter_i[0]}"
                else:
                    pass

        # checking integer and make seperate string
        string_N = ""
        numbers =  re.findall(r'\d+', split_text[0])
        numbers = [number for number in numbers if number not in STOP_NUMBERS]

        if len(numbers) == 1:
            string_N = f'{numbers[0]}'
        if len(numbers) > 1 and len(numbers) <3:
            if numbers[0] != numbers[1]:
                string_N = f'{numbers[0]}_{numbers[1]}'
        if len(numbers) == 0:
            string_N = ""

        # concatenate two string
        string = string_T+"_"+string_N

        column_metadata[col] = {
                "name": string,
                "unit": split_text[-1]
            }
        string = ""
        # print(column_metadata)
    checking_duplicates(column_metadata)

    all_metadata[name_] = column_metadata
    save_metadata(all_metadata, output_dir)

In [29]:
def metadata_mapping(metadata):
    _data = {
        key: value['name']
        for key, value in metadata.items()
    }
    print(_data)
    return _data

In [42]:
output_dir = Path.cwd().parent /"utils"

with open (output_dir /"metadata.json","r") as file: 
    metadata = json.load(file)
base_mapping = metadata_mapping(metadata['Base_data'])
population_mapping = metadata_mapping(metadata['Population_data'])
fertility_mapping = metadata_mapping(metadata['Fertility_data'])
mortality_mapping = metadata_mapping(metadata['Mortality_data'])
migration_mapping = metadata_mapping(metadata['Migration_data'])

{'Variant': 'VARIANT_', 'Region, subregion, country or area *': 'RSC_', 'Location code': 'LC_', 'ISO3 Alpha-code': 'IAC_3', 'Type': 'TYPE_', 'Year': 'YEAR_'}
{'Total Population, as of 1 January (thousands)': 'TP1_JAN', 'Total Population, as of 1 July (thousands)': 'TP1_JULY', 'Male Population, as of 1 July (thousands)': 'MP1_', 'Female Population, as of 1 July (thousands)': 'FP1_', 'Population Density, as of 1 July (persons per square km)': 'PD1_', 'Population Sex Ratio, as of 1 July (males per 100 females)': 'PSR_', 'Median Age, as of 1 July (years)': 'MA1_', 'Natural Change, Births minus Deaths (thousands)': 'NCB_', 'Rate of Natural Change (per 1,000 population)': 'RNC_', 'Population Change (thousands)': 'PC_', 'Population Growth Rate (percentage)': 'PGR_', 'Population Annual Doubling Time (years)': 'PAD_'}
{'Births (thousands)': 'BIRTHS_', 'Births by women aged 15 to 19 (thousands)': 'BWA_15_19', 'Crude Birth Rate (births per 1,000 population)': 'CBR_', 'Total Fertility Rate (live births per woman)': 'TFR_', 'Net Reproduction Rate (surviving daughters per woman)': 'NRR_', 'Mean Age Childbearing (years)': 'MAC_', 'Sex Ratio at Birth (males per 100 female births)': 'SRB_'}
{'Total Deaths (thousands)': 'TD_', 'Male Deaths (thousands)': 'MD_', 'Female Deaths (thousands)': 'FD_', 'Crude Death Rate (deaths per 1,000 population)': 'CDR_', 'Life Expectancy at Birth, both sexes (years)': 'LEB_', 'Male Life Expectancy at Birth (years)': 'MLE_', 'Female Life Expectancy at Birth (years)': 'FLE_', 'Life Expectancy at Age 15, both sexes (years)': 'LEA_15', 'Male Life Expectancy at Age 15 (years)': 'MLE_15', 'Female Life Expectancy at Age 15 (years)': 'FLE_15', 'Life Expectancy at Age 65, both sexes (years)': 'LEA_65', 'Male Life Expectancy at Age 65 (years)': 'MLE_65', 'Female Life Expectancy at Age 65 (years)': 'FLE_65', 'Life Expectancy at Age 80, both sexes (years)': 'LEA_80', 'Male Life Expectancy at Age 80 (years)': 'MLE_80', 'Female Life Expectancy at Age 80 (years)': 'FLE_80', 'Infant Deaths, under age 1 (thousands)': 'IDA_', 'Infant Mortality Rate (infant deaths per 1,000 live births)': 'IMR_', 'Live Births Surviving to Age 1 (thousands)': 'LBS_', 'Under-Five Deaths, under age 5 (thousands)': 'FDA_5', 'Under-Five Mortality (deaths under age 5 per 1,000 live births)': 'FM_', 'Mortality before Age 40, both sexes (deaths under age 40 per 1,000 live births)': 'MA4_40', 'Male Mortality before Age 40 (deaths under age 40 per 1,000 male live births)': 'MMA_40', 'Female Mortality before Age 40 (deaths under age 40 per 1,000 female live births)': 'FMA_40', 'Mortality before Age 60, both sexes (deaths under age 60 per 1,000 live births)': 'MA6_60', 'Male Mortality before Age 60 (deaths under age 60 per 1,000 male live births)': 'MMA_60', 'Female Mortality before Age 60 (deaths under age 60 per 1,000 female live births)': 'FMA_60', 'Mortality between Age 15 and 50, both sexes (deaths under age 50 per 1,000 alive at age 15)': 'MA1_15_50', 'Male Mortality between Age 15 and 50 (deaths under age 50 per 1,000 males alive at age 15)': 'MMA_15_50', 'Female Mortality between Age 15 and 50 (deaths under age 50 per 1,000 females alive at age 15)': 'FMA_15_50', 'Mortality between Age 15 and 60, both sexes (deaths under age 60 per 1,000 alive at age 15)': 'MA1_15_60', 'Male Mortality between Age 15 and 60 (deaths under age 60 per 1,000 males alive at age 15)': 'MMA_15_60', 'Female Mortality between Age 15 and 60 (deaths under age 60 per 1,000 females alive at age 15)': 'FMA_15_60'}
{'Net Number of Migrants (thousands)': 'NNM_', 'Net Migration Rate (per 1,000 population)': 'NMR_'}

In [43]:
Base_data.rename(columns=base_mapping, inplace=True)
Population_data.rename(columns=population_mapping, inplace=True)
Fertility_data.rename(columns=fertility_mapping, inplace=True)
Mortality_data.rename(columns=mortality_mapping, inplace=True)
Migration_data.rename(columns=migration_mapping, inplace=True)

Adding primary key to base data and foreign key to other

In [ ]:
Base_data.insert(0,'ID',range(1, len(data)+1))
Population_data.insert(0, 'ID', range(1, len(data)+1))
Mortality_data.insert(0, 'ID', range(1, len(data)+1))
Fertility_data.insert(0, 'ID', range(1, len(data)+1))
Migration_data.insert(0, 'ID', range(1, len(data)+1))

In [51]:
Base_data.to_csv(r"C:\Users\sandi\Documents\Study\project\World Demographic Index\Data\Processed_data\Base_data.csv", index=False)
Population_data.to_csv(r"C:\Users\sandi\Documents\Study\project\World Demographic Index\Data\Processed_data\Population_data.csv", index=False)
Fertility_data.to_csv(r"C:\Users\sandi\Documents\Study\project\World Demographic Index\Data\Processed_data\Fertility_data.csv", index=False)
Mortality_data.to_csv(r"C:\Users\sandi\Documents\Study\project\World Demographic Index\Data\Processed_data\Mortality_data.csv", index=False)
Migration_data.to_csv(r"C:\Users\sandi\Documents\Study\project\World Demographic Index\Data\Processed_data\Migration_data.csv", index=False)

In [ ]:
def SQL_structure(table_name, data_table):
    # make SQL column structure and save it on SQL folder.
    dtype_map = {
    'str': 'VARCHAR(64)',  
    'float64': 'DOUBLE PRECISION', # 64 bit floating point data
    'int64': 'BIGINT' # 8 byte (64 bit) int
    }

    output_dir = Path.cwd().parent / "SQL"

    for table,data_ in zip(table_name, data_table):
        sql = f"CREATE TABLE {table} (\n"
        for col, dtype in data_.dtypes.items():
            sql += f'   {col} {dtype_map.get(str(dtype), "TEXT")},\n' # get(key, default value)
            
        sql = sql.rstrip(",\n") + "\n" # right strip remove trailing ch from right side
        sql = sql + ")"

        with open(output_dir / f"{table}.sql", 'w') as f:
            f.write(sql)

In [ ]:
table_name = ['base_table','population_table','fertility_table','mortality_table','migration_table']
data_table = [Base_data, Population_data, Fertility_data, Mortality_data, Migration_data]
SQL_structure(table_name, data_table)

In [76]:
marraige_age_data = pd.read_csv(r"C:\Users\sandi\Documents\Study\project\World Demographic Index\Data\Age of mother at marriage, first and last birth.csv")
marraige_age_data

,Year,Median age at first birth,Median age at last birth,Median age at first marriage
0,1992,19.400000,32.799999,16.100000
1,1998,19.400000,30.799999,16.700001
2,2005,19.799999,28.700001,17.200001
3,2015,21.000000,27.799999,18.600000
4,2020,21.200001,27.600000,18.799999

In [186]:
TFR_statewise = pd.read_csv(r'C:\Users\sandi\Documents\Study\project\World Demographic Index\Data\state-wise-total-fertility-rate-data.csv')
TFR_statewise.sort_values(by = ['TFR 2023'])

                State  TFR 2023
4               Delhi       1.2
17         Tamil Nadu       1.3
21        West Bengal       1.3
13        Maharashtra       1.4
10          Karnataka       1.5
11             Kerala       1.5
8   Jammu and Kashmir       1.5
0      Andhra Pradesh       1.5
15             Punjab       1.5
18          Telangana       1.5
7    Himachal Pradesh       1.6
14             Odisha       1.7
20        Uttarakhand       1.7
5             Gujarat       1.8
6             Haryana       1.9
1               Assam       2.0
9           Jharkhand       2.1
3        Chhattisgarh       2.2
16          Rajasthan       2.3
12     Madhya Pradesh       2.4
19      Uttar Pradesh       2.6
2               Bihar       2.8

In [78]:
TFR_India_states = pd.read_csv(r"C:\Users\sandi\Documents\Study\project\World Demographic Index\Data\TFR  India and states.csv")
TFR_India_states

           Location  Year  TFR
0    Andhra Pradesh  1971  4.6
1    Andhra Pradesh  1972  4.7
2    Andhra Pradesh  1973  4.2
3    Andhra Pradesh  1974  4.6
4    Andhra Pradesh  1975  4.6
..              ...   ...  ...
925     West Bengal  2019  1.5
926     West Bengal  2020  1.4
927     West Bengal  2021  1.4
928     West Bengal  2022  1.4
929     West Bengal  2023  1.3

[930 rows x 3 columns]

In [85]:
TFR_India_states[TFR_India_states['Location'] == 'Himachal Pradesh']

             Location  Year  TFR
294  Himachal Pradesh  2014  1.7
295  Himachal Pradesh  2015  1.7
296  Himachal Pradesh  2016  1.7
297  Himachal Pradesh  2017  1.6
298  Himachal Pradesh  2018  1.6
299  Himachal Pradesh  2019  1.6
300  Himachal Pradesh  2020  1.5
301  Himachal Pradesh  2021  1.6
302  Himachal Pradesh  2022  1.5
303  Himachal Pradesh  2023  1.6

In [71]:
TFR_overTime = pd.read_csv(r"C:\Users\sandi\Documents\Study\project\World Demographic Index\Data\TFR over time in Indian state.csv")
TFR_overTime

           Location  Year  Rural TFR  Urban TFR
0    Andhra Pradesh  1971        4.8        3.8
1    Andhra Pradesh  1972        4.8        4.4
2    Andhra Pradesh  1973        4.3        3.7
3    Andhra Pradesh  1974        4.8        4.0
4    Andhra Pradesh  1975        4.8        3.6
..              ...   ...        ...        ...
925     West Bengal  2019        1.6        1.2
926     West Bengal  2020        1.5        1.1
927     West Bengal  2021        1.5        1.2
928     West Bengal  2022        1.5        1.2
929     West Bengal  2023        1.4        1.1

[930 rows x 4 columns]

In [70]:
table_name = ['marraige_age_data', 'TFR_India_states', 'TFR_IndianStates_countries' , 'TFR_overTime']
data_table = [marraige_age_data, TFR_India_states, TFR_IndianStates_countries, TFR_overTime]
SQL_structure(table_name, data_table)

Extracting low & high TFR rate countries

In [174]:
# only keep type: Country/Area and drop other rows
data = data[data['Type'] == 'Country/Area']
data

15,Index,Variant,"Region, subregion, country or area *",Notes,Location code,ISO3 Alpha-code,ISO2 Alpha-code,SDMX code**,Type,Parent code,...,"Male Mortality before Age 60 (deaths under age 60 per 1,000 male live births)","Female Mortality before Age 60 (deaths under age 60 per 1,000 female live births)","Mortality between Age 15 and 50, both sexes (deaths under age 50 per 1,000 alive at age 15)","Male Mortality between Age 15 and 50 (deaths under age 50 per 1,000 males alive at age 15)","Female Mortality between Age 15 and 50 (deaths under age 50 per 1,000 females alive at age 15)","Mortality between Age 15 and 60, both sexes (deaths under age 60 per 1,000 alive at age 15)","Male Mortality between Age 15 and 60 (deaths under age 60 per 1,000 males alive at age 15)","Female Mortality between Age 15 and 60 (deaths under age 60 per 1,000 females alive at age 15)",Net Number of Migrants (thousands),"Net Migration Rate (per 1,000 population)"
2594,2595,Estimates,Burundi,NaN,108,BDI,BI,108,Country/Area,910,...,640,591,291,310,273,424,455,396,- 13,-5.9
2595,2596,Estimates,Burundi,NaN,108,BDI,BI,108,Country/Area,910,...,637,585,288,309,270,421,453,392,- 13,-5.7
2596,2597,Estimates,Burundi,NaN,108,BDI,BI,108,Country/Area,910,...,634,582,287,307,268,419,451,389,- 14,-5.8
2597,2598,Estimates,Burundi,NaN,108,BDI,BI,108,Country/Area,910,...,630,578,285,305,266,416,448,387,- 15,-6.2
2598,2599,Estimates,Burundi,NaN,108,BDI,BI,108,Country/Area,910,...,628,575,283,304,264,414,447,385,- 15,-5.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21978,21979,Estimates,Wallis and Futuna Islands,2.0,876,WLF,WF,876,Country/Area,957,...,92,94,29,27,31,79,82,76,- 0,-14.3
21979,21980,Estimates,Wallis and Futuna Islands,2.0,876,WLF,WF,876,Country/Area,957,...,90,92,28,26,30,77,81,75,- 0,-6.1
21980,21981,Estimates,Wallis and Futuna Islands,2.0,876,WLF,WF,876,Country/Area,957,...,103,100,32,31,33,88,94,83,- 0,-6.1
21981,21982,Estimates,Wallis and Futuna Islands,2.0,876,WLF,WF,876,Country/Area,957,...,87,89,27,25,29,75,78,72,- 0,-11.0
21982,21983,Estimates,Wallis and Futuna Islands,2.0,876,WLF,WF,876,Country/Area,957,...,86,88,27,25,29,74,77,71,- 0,-9.4

In [175]:
# check any null values by regular expression. 
is_invalid = data[data['Total Fertility Rate (live births per woman)'].astype(str).str.contains(r'[^0-9.]', na=False)] # check any null values
print(is_invalid['Total Fertility Rate (live births per woman)'].unique())

[]

In [176]:
# check nan values or null values by numeric then check
is_invalid = pd.to_numeric(data['Total Fertility Rate (live births per woman)'], errors='coerce').isna() & data['Total Fertility Rate (live births per woman)'].notna() 
# first convert into numeric ignoring the error. then check na values
print(is_invalid.unique())  # atleast one invalid string row
invalid_rows = data[is_invalid] 
print('print the invalid values:', invalid_rows['Total Fertility Rate (live births per woman)'].unique())
print('invalid rows:', invalid_rows[['Region, subregion, country or area *','Total Fertility Rate (live births per woman)']])

[False]
print the invalid values: []
invalid rows: Empty DataFrame
Columns: [Region, subregion, country or area *, Total Fertility Rate (live births per woman)]
Index: []

In [177]:
# clean this first convert to numeric then dropna
col = 'Total Fertility Rate (live births per woman)'
data[col] = pd.to_numeric(data[col], errors='coerce')
data = data.dropna(subset=[col])

In [178]:
data = data[data['Total Fertility Rate (live births per woman)'] <= 2.1]
Low_TFR_rate = data[['Region, subregion, country or area *', 'Total Fertility Rate (live births per woman)','Parent code','Year']]

In [179]:
Low_TFR_rate.sort_values(by = ['Total Fertility Rate (live births per woman)'], inplace=True)

In [180]:
Low_TFR_rate.reset_index(drop = True)

15,"Region, subregion, country or area *",Total Fertility Rate (live births per woman),Parent code,Year
0,"China, Macao SAR",0.66,906,2022
1,"China, Macao SAR",0.66,906,2023
2,Saint Barthélemy,0.71,915,2018
3,"China, Hong Kong SAR",0.71,906,2022
4,"China, Hong Kong SAR",0.72,906,2023
...,...,...,...,...
4318,Curaçao,2.10,915,2013.0
4319,Curaçao,2.10,915,2004.0
4320,United States Virgin Islands,2.10,915,2022
4321,Tunisia,2.10,912,2019
4322,Canada,2.10,905,1971

In [181]:
Low_TFR_rate['Parent code']=Low_TFR_rate['Parent code'].astype(int)
Low_TFR_rate['Year']=Low_TFR_rate['Year'].astype(int)

In [182]:
Low_TFR_rate = Low_TFR_rate[Low_TFR_rate['Year'] == 2023].reset_index(drop=True)
Low_TFR_rate

15,"Region, subregion, country or area *",Total Fertility Rate (live births per woman),Parent code,Year
0,"China, Macao SAR",0.66,906,2023
1,"China, Hong Kong SAR",0.72,906,2023
2,Republic of Korea,0.72,906,2023
3,Saint Barthélemy,0.80,915,2023
4,"China, Taiwan Province of China",0.87,906,2023
...,...,...,...,...
125,Martinique,2.01,915,2023
126,Cook Islands,2.05,957,2023
127,Venezuela (Bolivarian Republic of),2.08,931,2023
128,Guadeloupe,2.09,915,2023
129,United States Virgin Islands,2.09,915,2023

In [183]:
Low_TFR_rate.to_csv(r'C:\Users\sandi\Documents\Study\project\World Demographic Index\Data\Processed_data\Low_TFR_countries.csv', index=False)

In [184]:
data_table = [Low_TFR_rate]
table_name = ['Low_TFR_rate']

SQL_structure(table_name, data_table)